### PR TITLE
feat: imgix-go@v2.0.0

### PR DESCRIPTION
**Pull request by ericdeansanchez**
The purpose of this PR is to push this URL creation API  towards
parity with the rest of our SDK. Other than naming and a few minor
program flow changes, the only functional changes made here can
be observed in the test suite.

W.r.t. the above, `signatureBase`s are now being generated in
accordance with `imgix-core-js` et al.

### CODE REVIEW

**Comment by ericdeansanchez** [comment]
@frederickfogerty Thanks! Yeah, I haven't even dug into the tests yet. That is, I've only been touching tests if something has failed as a result of refactoring (renaming, etc.). We are in the same camp. I think things should be unit-tested and then put through integration testing.

Also another reason I'm a proponent of builder-y patterns (the actual pattern), as it allows for more fine grain testing without having to write a bunch of code (which can be flawed) or helpers just to test code/state, etc.

**Comment by ericdeansanchez** [comment]
**Naming**:

Right now, the `Builder` is named generically. This will probably be the case while I'm still mulling over the overall module structure. Suggestions?

**Comment by sherwinski** [comment]
> **Naming**:
> 
> Right now, the `Builder` is named generically. This will probably be the case while I'm still mulling over the overall module structure. Suggestions?

My strong feeling would be `URLBuilder` as it is more specific than `Builder` and matches the rest of our SDK libraries.

**Comment by ericdeansanchez** [comment]
Agreed! Okay, I will rename `Builder` to `URLBuilder`.

**Comment by ericdeansanchez** [comment]
This has been a great development branch to try things out. In order to clean up the history I've made a new PR (#7) and will be closing this one.

**Pull request closed without merging**
